### ISSUE TITLE
Bug: vector_utils.h does not conform to c98

### ISSUE THREAD

**Issue by julianhartmer** [eteran/c-vector#39]
The macros in vector_utils.h use declaration statements in for loops, which was introduced in c99. However, in the README it states that the library is c98 conforming, which is not the case for this file. This should either be documented in vector_utils.h or the functions should be removed or fixed.

**Comment by eteran** [comment]
Good catch, I'll update soon 🙂

**Comment by eteran** [comment]
I believe it is fixed. Please re-open if I am incorrect.
