### ISSUE TITLE
Is c-vector thread-safe?

### ISSUE THREAD

**Issue by salocinx** [eteran/c-vector#4]
Hi. I am trying to use c-vector in FreeRTOS. It does work fine when using within a single task, but I run into problems when trying to use it across two tasks. Is this use case tested or undefined? Thanks.

**Comment by eteran** [comment]
Hi. So c-vector has the same basic thread safety as something an a C-array. That is, multiple readers should work just fine, but multiple writers must be synchronized by the caller.

**Comment by salocinx** [comment]
Thanks!
