### ISSUE TITLE
why while(0)

### ISSUE THREAD

**Issue by mmj-the-fighter** [eteran/c-vector#67]
Please explain the rationale behind keeping the following pattern in the code
do{
...
 } while (0)

**Comment by mmj-the-fighter** [comment]
i replaced do{ ... } while(0) with {..} for #define cvector_push_back(vec, value) , and it worked.

**Comment by mmj-the-fighter** [comment]
worked modification
#define cvector_push_back(vec, value)                                 \
     {                                                              \
        size_t cv_cap__ = cvector_capacity(vec);                      \
        if (cv_cap__ <= cvector_size(vec)) {                          \
            cvector_grow((vec), cvector_compute_next_grow(cv_cap__)); \
        }                                                             \
        (vec)[cvector_size(vec)] = (value);                           \
        cvector_set_size((vec), cvector_size(vec) + 1);               \
    }

**Comment by eteran** [comment]
The rationale is that it is a common pattern to ensure that the code properly acts like a function call.

For example, you'll notice that the do while version requires a semicolon but yours does not.
