### ISSUE TITLE
Performance VS std::vector

### ISSUE THREAD

**Issue by jordan4ibanez** [eteran/c-vector#72]
As I cannot find any benchmarking information I thought I'd simply ask.

What is the performance like in comparison to C++ std::vector?

**Comment by eteran** [comment]
In general, the performance should be comparable to that of `std::vector`. That is:

O(1) element access

Amortized constant performance for push_back (meaning that it will *usually* not need to resize the array, but will sometimes need to, in which case, there is a O(n) cost to adjusting capacity.
