### ISSUE TITLE
Why cvector_at return &(vec)[n]

### ISSUE THREAD

**Issue by GoodenoughPhysicsLab** [eteran/c-vector#73]
```
/**
 * @brief cvector_at - returns a reference to the element at position n in the vector.
 * @param vec - the vector
 * @param n - position of an element in the vector.
 * @return the element at the specified position in the vector.
 */
#define cvector_at(vec, n) \
    ((vec) ? (((int)(n) < 0 || (size_t)(n) >= cvector_size(vec)) ? NULL : &(vec)[n]) : NULL)
```
in c-plus-plus, vector::at is a safe way to get a element instead of its address, I think it's a bug.
If you agree with me, please let me send a pr.

**Comment by eteran** [comment]
C doesn't have references, and pointers are a close approximation to them.

Also, if it were to return a value, what would you have it return if the index is out of range (as there are no exceptions in C).

So...

I don't feel it's a "bug" but is an implementation choice based on what we have to work with.

However, feel free to submit a PR with your proposed alternatives. If i agree it is an improvement, then it will get merged.

**Comment by eteran** [comment]
There also is a test for the at function in the test suite.

**Comment by GoodenoughPhysicsLab** [comment]
if the index is out of range, we can abort.

return a address will makes the usage like:
```
cvector(char*) p = NULL;
cvector_init(p, 1, free_str_);

(*cvector_at(p, 0))[0] // p[0][0]
```

**Comment by GoodenoughPhysicsLab** [comment]
abort is not good, but we can use error code instead

**Comment by GoodenoughPhysicsLab** [comment]
oh, I realized the problem of exception.

**Comment by GoodenoughPhysicsLab** [comment]
how about use assert to check the range?

**Comment by GoodenoughPhysicsLab** [comment]
> C doesn't have references, and pointers are a close approximation to them.
The vec[n] equals to *(vec + n), and cvector use macro to provide the api. So, I think that it's already similar to a reference. That's why I think that there is no need to get its address.

I'm not a native English speaker, some meanings may be expressed inaccurately.

**Comment by GoodenoughPhysicsLab** [comment]
I realized what you have said. What I was trying to do is not assignable.
As you say, C do not have reference.

**Comment by eteran** [comment]
Appreciate you taking a look! 👍

**Comment by GoodenoughPhysicsLab** [comment]
I'd find a solution!
