### ISSUE TITLE
False result from copy a vector

### ISSUE THREAD

**Issue by hieutran29** [eteran/c-vector#8]
When I tried to copy a vector to a new one using the operator `=`, everything went fine until I changed a value of the original vector, the second vector changed alongside the original vector. It is expected that the second vector didn't change whether the original one made any change.
I suggest implementing a function `cvector_copy()` to fix the issue.

**Comment by eteran** [comment]
Yea, this isn't c++, so we can't overload the assignment operator. But sure, your `cvector_copy` seems reasonable enough :-)
